### ISSUE TITLE
SpringBoot 结合Flyway实现数据库自动迁移

### ISSUE THREAD

**Issue by babyachievement** [babyachievement/notes#12]
Flyway是一个数据库迁移工具，实现了以下功能：
1. 数据库脚本的版本控制
2. 基于版本的数据库自动迁移

SpringBoot可以直接集成Flyway实现数据库的自动迁移。

使用方法

1. 添加flyway-core依赖
```xml
<dependency>
	<groupId>org.flywaydb</groupId>
	<artifactId>flyway-core</artifactId>
</dependency>
```
2. 添加flyway配置

在application.yml或application.properties文件中添加flyway的配置，如下所示：
```yaml
spring:
  jpa:
    hibernate:
      ddl-auto: validate
    database: mysql
  datasource:
      url: jdbc:mysql://localhost:3306/demo
      username: root
      password: password

flyway:
  locations: classpath:db/migration/mysql  #指定数据库迁移脚本位置
```

这里我使用了datasource为flyway提供数据库连接，并指定了迁移脚本的所在位置，默认位置为resources/.db/migration,这里我添加了数据库厂商目录。Flyway对迁移脚本文件的命名有一定要求，命名格式是：
```
V1_1__Init.sql或R1_1__Init.sql
```
其中V和R是前缀，1_1是版本号，版本号后边是'__'（两个下划线），然后是脚本描述，后缀是sql。

V和R分别代表两种不同的迁移策略：
* V:version,基于版本的迁移，每个脚本只会被应用一次 
* R：repeateable，脚本的checksum改变时就会被重复应用

执行SpringBootApplication程序，数据库会自动创建schema_version表，用于跟踪数据库迁移记录。
