### ISSUE TITLE
SpringBoot 使用alibaba druid连接池

### ISSUE THREAD

**Issue by babyachievement** [babyachievement/notes#13]
SpringBoot自动配置使用池化DataSource，选择特定实现的算法是：
* 考虑到性能和并发性优选选择Tomcat 池化DataSource，所以如果它可用总是选择它
* 否则，如果HikariCP可用，则使用
* 如果Tomcat 池化DataSource和HikariCPU都不可用，而Commons DBCP可用，将使用DBCP，但是不推荐在生产环境中使用，因为它的支持已经过期
* 最后，如果Commons DBCP2可用，则使用

如果使用spring-boot-starter-jdbc或spring-boot-starter-data-jpa启动器，将会自动获取tomcat-jdbc依赖。不过可以完全绕开这个算法，使用<code>spring.datasource.type</code>属性指定连接池。这对于运行在tomcat中的程序，tomcat-jdbc默认被提供时尤其重要。

可以随时手动配置连接池。如果定义了自己的<code>DataSource</code>bean，自动配置将不会发生。

可以使用application.yml设置连接池，如下：
```yaml
spring:
  profiles: dev
  datasource:
    url: jdbc:mysql://localhost:3306/demo
    username: root
    password: password
    type: com.alibaba.druid.pool.DruidDataSource
    initialSize: 1 # 配置初始化大小
    maxActive: 20 # 最大
    minIdle: 1  # 最小
    maxWait: 60000 # 获取连接等待超时的时间
```

如上所示，通过设置spring.datasource.type的值为com.alibaba.druid.pool.DruidDataSource，设置了连接池。
更多druid配置属性参考[配置_DruidDataSource参考配置](https://github.com/alibaba/druid/wiki/%E9%85%8D%E7%BD%AE_DruidDataSource%E5%8F%82%E8%80%83%E9%85%8D%E7%BD%AE)

 参考：
[boot features sql](https://docs.spring.io/spring-boot/docs/current/reference/html/boot-features-sql.html)
